--- 
title: "Sistemas de Informaçãoes Geográficas para Transporte"
author: "Édipo H. Cremon"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Introdução ao SIG

É comum nos depararmos com uma série de nomenclaturas cuja diferenciação torna-se nebulosa até mesmo para quem está atuando na área há bastante tempo. É comum vermos pessoas usando os termos geoprocessamento, geotecnologias e SIG (Sistema de Informação Geográfica) como sinônimos. Mas não são! Inclusive há certa hierarquia dentro destes conceitos.

**Geoprocessamento**

Corresponde “a área do conhecimento que utiliza técnicas matemáticas e computacionais para o tratamento da informação geográfica e que vem influenciando de maneira crescente as áreas de Cartografia, Análise de Recursos Naturais, Transportes, Comunicações, Energia e Planejamento Urbano e Regional” (Câmara e Davis, 2004).

**Geotecnologias**

* Conjunto de tecnologias para coleta, processamento, análise e disponibilização de informação com referência geográfica

* As geotecnologias são compostas por soluções em hardware, software e peopleware (recursos humanos) que juntos se constituem em poderosas ferramentas para tomada de decisão

* As geotecnologias estão entre os três mercados emergentes mais importantes da atualidade, junto com a nanotecnologia e a biotecnologia (Revista Nature, jan2004)

**Sistemas de Informação Geográfica - SIG**

As ferramentas computacionais para Geoprocessamento, chamadas de SIG, permitem realizar análises complexas, ao integrar dados de diversas fontes e ao criar bancos de dados georreferenciados. Tornam ainda possível automatizar a produção de documentos cartográficos (Câmara e Davis, 2004).

Podemos dizer que é convergência de diferentes disciplinas onde o espaço (computacionalmente representado) é a linguagem comum. Como inúmeros campos da ciência (geografia, geologia, agronomia, engenharias ambiental, florestal, cartográfica e agrimensura, do transporte, etc) tratam de dados com uma localização geográfica, logo o SIG se faz como uma poderosa ferramenta de análise destes campos.

Pode-se definir SIG como um conjunto de ferramentas computacionais composto de equipamentos e programas que por meio de técnicas, integra dados (das mais diversas fontes), pessoas e instituições, de forma a tornar possível a coleta, o armazenamento, a análise e a disponibilização, a partir de dados georreferenciados, de informações produzidas por meio de aplicações, visando maior facilidade, segurança e agilidade nas atividades humanas referentes ao monitoramento, planejamento e tomada de decisão relativas ao espaço geográfico.


**Informação Geográfica (IG)**

Por sua vez, a informação geográfica pode ser entendida como:

* Informação sobre lugares na superfície da Terra
* Conhecimento sobre onde alguma coisa está
* Conhecimento sobre o que está em uma dada localização (GOODCHILD, 1997)

Nesse contexto, o adjetivo “geográfico” corresponde a informação que está sobre a superfície da Terra. Dado essa restrição é comum ser usado o termo informação espacial, uma vez que o termo espacial não se restringe apenas a informações sobre a superfície terrestre, se referindo genericamente a qualquer lugar no espaço. Em ambiente SIG é comum que diversas análises sejam denominadas de análise espacial, não análise geográfica, já que podem ser aplicadas a diversas finalidades que podem ser mais abrangentes que a algo que está sobre a superfície terrestre. Também é comum encontrar o termo informação geoespacial ou geoinformação que na prática tem a mesma conotação que informação espacial, ou seja, mais abrangente que informação geográfica.

**Ciência da Informação Geográfica**

Dado que a ciência da informação estuda os temas fundamentais decorrentes da criação, manuseio, armazenamento e uso da informação. Logo, a Ciência da Informação Geográfica estuda os temas decorrentes da IG.
Na bibliografia é comum constatar o uso dos termos ciência da informação geográfica, geomática, ciência da informação espacial e engenharia da geoinformação. De autor pra autor esses termos podem ter ligeiras diferenças, mas em linhas gerais são denominações muito próximas.


A ciência da informação geográfica está mais que consolidada no meio acadêmico e prova disso são eventos e revistas científicas dedicadas à sua temática. Como exemplo temos as revistas Geographical Information Science, Journal of Geographic Information System e o International Journal of Geo-Information.


**SIG-T**

O SIG permite a integração dados geográficos (georreferenciados) e não-geográficos, facilitando a coleta, o armazenamento, a análise e a disponibilização, a partir de dados georreferenciados. Na área de transporte, o SIG constitui em uma importante ferramenta no tratamento de toda a informação base (estatística ou cartográfica) referente às locações, às deslocações, aos fluxos e aos motivos pelos quais existe o transporte de algo. Dado esse potencial, há um aumento de aplicações de SIG no mercado e na academia, fazendo surgir o nome de SIG- T (em inglês: GIS-T - Geographical Information Systems in Transportation).

A consolidação do SIG-T como uma área científica pode ser observada na inserção do tema em revistas especializadas de transporte tradicionais (por exemplo, o Journal of Advanced Transportation e o Journal of Transportation Planning and Technology). Outro exemplo desta consolidação é a realização de eventos científicos voltados ao tema, com destaque é interessante mencionar o Annual GIS for Transportation Symposium.


